import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "../components/Navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <a href="#main-content" className="skip-link" style={{position: 'absolute', left: '-999px', top: 'auto', width: '1px', height: '1px', overflow: 'hidden', zIndex: 1000, background: '#fff', color: '#171717', padding: '8px', borderRadius: '4px'}} onFocus={e => {e.currentTarget.style.left = '8px'; e.currentTarget.style.width = 'auto'; e.currentTarget.style.height = 'auto';}}>Skip to main content</a>
        <nav role="navigation" aria-label="Main navigation">
          <Navigation />
        </nav>
        <main id="main-content" tabIndex={-1} role="main">
          {children}
        </main>
      </body>
    </html>
  );
}
